trigger:
- main

stages:
- stage: Terraform_init_plan

  pool:
    vmImage: ubuntu-latest

  jobs:
 
  - job: terraform_init_plan

    steps:
    
    - task: TerraformInstaller@0
      displayName: Install TF 0.15.0
      inputs:
        terraformVersion: '0.15.0'